### ISSUE TITLE
Read Python.txt file

### ISSUE THREAD

**Issue by 23bca299** [vtcbca/internal-exam-23bca299#2]
while i read the file it showing empty..

**Comment by amitvtcbb** [comment]
please check , does your file contain the data or not? if your file contain data please attach full code here show i can help you.

**Comment by 23bca274** [comment]
> while i read the file it showing empty..

Do as following :- 

1. Create file OR open file in writing mode "w".
2. Create an empty list and take input from user and close the file.
3. Open file in reading mode "r".
4. Take a variable and store data in it. Ex:- file_content = f.read() and close the file.
5. Take another variable in which you wanna store reversed content with using " Indexing " and print it .
Ex :- reversed_content = file_content [ : : -1 ]
        print(reversed_content)

Hope this may help you.
